# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\myCode\gammaTool\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_FileOpenMain = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_FileOpenMain.setObjectName("pushButton_FileOpenMain")
        self.horizontalLayout.addWidget(self.pushButton_FileOpenMain)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton_drawMain = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_drawMain.setObjectName("toolButton_drawMain")
        self.horizontalLayout.addWidget(self.toolButton_drawMain)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_TextViewerMain = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_TextViewerMain.setObjectName("textEdit_TextViewerMain")
        self.verticalLayout.addWidget(self.textEdit_TextViewerMain)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_FileOpenSub = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_FileOpenSub.setObjectName("pushButton_FileOpenSub")
        self.horizontalLayout_2.addWidget(self.pushButton_FileOpenSub)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.toolButton_drawSub = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_drawSub.setObjectName("toolButton_drawSub")
        self.horizontalLayout_2.addWidget(self.toolButton_drawSub)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.textEdit_TextViewerSub = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_TextViewerSub.setObjectName("textEdit_TextViewerSub")
        self.verticalLayout_2.addWidget(self.textEdit_TextViewerSub)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_reform = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_reform.setObjectName("pushButton_reform")
        self.verticalLayout_3.addWidget(self.pushButton_reform)
        self.pushButton_extend = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_extend.setObjectName("pushButton_extend")
        self.verticalLayout_3.addWidget(self.pushButton_extend)
        self.pushButton_balance = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_balance.setObjectName("pushButton_balance")
        self.verticalLayout_3.addWidget(self.pushButton_balance)
        self.pushButton_smooth = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_smooth.setObjectName("pushButton_smooth")
        self.verticalLayout_3.addWidget(self.pushButton_smooth)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout_4.addWidget(self.textEdit_result)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(100, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.toolButton_copy = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_copy.setObjectName("toolButton_copy")
        self.horizontalLayout_6.addWidget(self.toolButton_copy)
        self.toolButton_drawResult = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_drawResult.setObjectName("toolButton_drawResult")
        self.horizontalLayout_6.addWidget(self.toolButton_drawResult)
        self.horizontalLayout_6.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_FileOpenMain.setText(_translate("MainWindow", "open"))
        self.toolButton_drawMain.setText(_translate("MainWindow", "draw"))
        self.pushButton_FileOpenSub.setText(_translate("MainWindow", "open"))
        self.toolButton_drawSub.setText(_translate("MainWindow", "draw"))
        self.pushButton_reform.setText(_translate("MainWindow", "gammaReform"))
        self.pushButton_extend.setText(_translate("MainWindow", "gammaExten"))
        self.pushButton_balance.setText(_translate("MainWindow", "gammaBalance"))
        self.pushButton_smooth.setText(_translate("MainWindow", "gammaSmooth"))
        self.toolButton_copy.setText(_translate("MainWindow", "copy"))
        self.toolButton_drawResult.setText(_translate("MainWindow", "draw"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
